# API Interfaces to control the simulator
#
# @author n1ghts4kura
# @date 2026-3-15
#

import json
import os
from uuid import uuid4
from enum import Enum
from pydantic import BaseModel, Field
from websocket import create_connection, WebSocketTimeoutException

from src.logger import make_logger
logger = make_logger("simulator")


# === Types ===
# 1. Action Types: modify the state of the bot (e.g., move, rotate, fire)
# 2. Response Types: provide feedback on the result of an action (e.g., success, failure, error message)
# =============


class Action(BaseModel):
    """Basic API Action Interface"""

    request_id: str = Field(default_factory=lambda: uuid4().hex, description="A unique ID for this action request, generated automatically if not provided")

    team: str = Field(..., description="Team the bot belongs to, either 'red' or 'blue'")

    timeout: int = Field(
        default=-1,
        ge=-1,
        description=(
            "Execution timeout budget in milliseconds for Unity-side action processing. "
            "Use -1 to wait indefinitely (no execution deadline)."
        ),
    )

    def to_datapacket_str(self) -> str:
        """
        Convert an Action instance to a dictionary format suitable for sending as a data packet to the simulator.

        Format:
        ```
        {
            "request_id": "an_unique_id_for_this_request", # always required; generated through `uuid.uuid4()`   
            "timeout": 5000, # always required; execution timeout in milliseconds; -1 means wait indefinitely
            "team": "red", # or "blue"; always required; should be set by the client based on the team the bot belongs to  
            "command": "the_command_name", # always required; same as the class name of the Action (e.g., "ChassisForwardAction")  
            "value": "...", # the content of the Action instance converted to a dictionary; always required; should be generated by the `dict()` method of the Action instance  
        }
        ```
        """

        command = self.__class__.__name__ # dynamic because of INHERITANCE
        value = self.model_dump(exclude={"request_id", "team", "timeout"}) # exclude common fields that are already included in the datapacket)

        datapacket = {
            "request_id": self.request_id,
            "timeout": self.timeout,
            "team": self.team,
            "command": command,
            "value": value,
        }

        return json.dumps(datapacket, ensure_ascii=False)
    

class Response(BaseModel):
    """Basic API Response Interface"""

    request_id: str = Field(..., description="The unique ID of the corresponding request/action that this response is for")

    success: bool = Field(..., description="Indicates if the action was successful")

    # value: str = Field("", description="The content of the response, which can be a success message, error message, or any relevant information returned by the simulator")


class StringResponse(Response):
    """A simple Response type where the value is just a string message"""

    value: str = Field("", description="The content of the response as a string, which can be a success message, error message, or any relevant information returned by the simulator")


class FloatResponse(Response):
    """A simple Response type where the value is a float number"""

    value: float = Field(0.0, description="The content of the response as a float number, which can be any relevant information returned by the simulator (e.g., current speed, angle, etc.)")


# --- 1. Settings ---
# - (1) Bot Control Mode Settings

class BotControlMode(str, Enum):
    """Enumeration for Bot Control Modes"""

    INDEPENDENT = "independent" # Chassis and turret can be controlled independently
    CHASSIS_FOLLOW_TURRET = "chassis_follow_turret" # Chassis follows turret direction
    TURRET_FOLLOW_CHASSIS = "turret_follow_chassis" # Turret follows chassis direction


class BotControlModeSetAction(Action):
    """API Interface for Bot Control Mode Action"""

    mode: BotControlMode = Field(..., description="Bot control mode to set")


class BotControlModeGetAction(Action):
    """API Interface for Get Bot Control Mode Action"""

    pass


# - (2) Bot Speed Settings

class ChassisLinearSpeedSetAction(Action):
    """API Interface for Set Chassis Linear Speed Action"""

    speed: float = Field(..., description="Linear speed to set in meters per second")


class ChassisLinearSpeedGetAction(Action):
    """API Interface for Get Chassis Linear Speed Action"""

    pass


class ChassisAngularSpeedSetAction(Action):
    """API Interface for Set Chassis Angular Speed Action"""

    speed: float = Field(..., description="Angular speed to set in degrees per second")


class ChassisAngularSpeedGetAction(Action):
    """API Interface for Get Chassis Angular Speed Action"""

    pass


# - (3) Turret Pitch Limit

class TurretPitchLimitSetAction(Action):
    """API Interface for Set Turret Pitch Limit Action"""

    value: float = Field(..., description="Turret pitch limit to set in degrees. Both positive and negative values are allowed, representing the maximum pitch up and down angles respectively.")


class TurretPitchLimitGetAction(Action):
    """API Interface for Get Turret Pitch Limit Action"""

    pass


# ------------------
# --- 2. Actions ---
# - (1) Chassis

class ChassisForwardAction(Action):
    """
    API Interface for Chassis Forward Action
    """

    distance: float = Field(..., description="Distance to move forward in meters")


class ChassisBackwardAction(Action):
    """API Interface for Chassis Backward Action"""

    distance: float = Field(..., description="Distance to move backward in meters")


class ChassisStrafeLeftAction(Action):
    """API Interface for Chassis Strafe Left Action"""

    distance: float = Field(..., description="Distance to strafe left in meters")


class ChassisStrafeRightAction(Action):
    """API Interface for Chassis Strafe Right Action"""

    distance: float = Field(..., description="Distance to strafe right in meters")


class ChassisRotateClockwiseAction(Action   ):
    """API Interface for Chassis Rotate Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate clockwise in degrees")


class ChassisRotateCounterClockwiseAction(Action):
    """API Interface for Chassis Rotate Counter-Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate counter-clockwise in degrees")


# - (2) Turret


class TurretRotateClockwiseAction(Action):
    """API Interface for Turret Rotate Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate turret clockwise in degrees")


class TurretRotateCounterClockwiseAction(Action):
    """API Interface for Turret Rotate Counter-Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate turret counter-clockwise in degrees")


class TurretRotatePitchAction(Action):
    """API Interface for Turret Pitch Up Action"""

    angle: float = Field(..., description="Angle to pitch turret up in degrees")


class TurretFireAction(Action):
    """API Interface for Turret Fire Action"""

    pass


# ===========

_BASE_URL = os.getenv("SIMULATOR_WS_URL", "ws://localhost:8765/ws")
_CONN_TIMEOUT = 3000 # default timeout for connection attempts in milliseconds
_WS_ORIGIN = os.getenv("SIMULATOR_WS_ORIGIN")
_WS_SUBPROTOCOL = os.getenv("SIMULATOR_WS_SUBPROTOCOL")


def _local_error_response(action: Action, message: str) -> str:
    """Build a JSON response for transport-layer failures on Python side."""

    return json.dumps(
        {
            "request_id": action.request_id,
            "success": False,
            "value": message,
        },
        ensure_ascii=False,
    )

def request(
    action: Action,
    url: str = _BASE_URL,
    conn_timeout: int = _CONN_TIMEOUT,
) -> str:
    """
    Send an Action to the Unity simulator via WebSocket and receive a Response.

    Args:
        action (Action): The Action instance to send to the simulator.
        url (str, optional): The WebSocket URL of the simulator. Defaults to _BASE_URL.
        conn_timeout (int, optional): Timeout for connection and socket I/O in milliseconds. Defaults to _CONN_TIMEOUT.

    Notes:
        `action.timeout` is forwarded to Unity as execution timeout budget.
        `action.timeout=-1` means no execution deadline (wait indefinitely on Unity side).
        `conn_timeout` is local Python transport timeout and is independent from `action.timeout`.

    Returns:
        str: The raw response string received from the simulator. In a real implementation, you would typically parse this into a Response object.
    """

    logger.debug(f"Sending action to simulator: {action}")

    ws = None
    try:
        timeout_sec = conn_timeout / 1000
        if _WS_ORIGIN and _WS_SUBPROTOCOL:
            ws = create_connection(
                url,
                timeout=timeout_sec,
                origin=_WS_ORIGIN,
                subprotocols=[_WS_SUBPROTOCOL],
            )
        elif _WS_ORIGIN:
            ws = create_connection(
                url,
                timeout=timeout_sec,
                origin=_WS_ORIGIN,
            )
        elif _WS_SUBPROTOCOL:
            ws = create_connection(
                url,
                timeout=timeout_sec,
                subprotocols=[_WS_SUBPROTOCOL],
            )
        else:
            ws = create_connection(url, timeout=timeout_sec)

        datapacket_str = action.to_datapacket_str()
        ws.send(datapacket_str)
        response_str = ws.recv()

        logger.debug(f"Received response from simulator: {response_str}")

        return response_str if isinstance(response_str, str) else str(response_str) 

    except WebSocketTimeoutException:
        logger.error(
            f"WebSocket transport timed out after {conn_timeout} ms when sending action: {action}"
        )
        return _local_error_response(action, f"error: transport timeout ({conn_timeout} ms)")

    except Exception as e:
        logger.error(f"Error during WebSocket communication: {e}")
        return _local_error_response(action, f"error: transport exception: {str(e)}")

    finally:
        if ws is not None:
            try:
                ws.close()
            except Exception:
                pass


__all__ = [
    "Action",
    "Response",
    "StringResponse",
    "BotControlMode",
    "BotControlModeSetAction",
    "BotControlModeGetAction",
    "FloatResponse",
    "ChassisLinearSpeedSetAction", 
    "ChassisLinearSpeedGetAction",
    "ChassisAngularSpeedSetAction",
    "ChassisAngularSpeedGetAction",
    "TurretPitchLimitSetAction",
    "TurretPitchLimitGetAction",
    "ChassisForwardAction",
    "ChassisBackwardAction",
    "ChassisStrafeLeftAction",
    "ChassisStrafeRightAction",
    "ChassisRotateClockwiseAction",
    "ChassisRotateCounterClockwiseAction",
    "TurretRotateClockwiseAction",
    "TurretRotateCounterClockwiseAction",
    "TurretRotatePitchAction",
    "TurretFireAction",
    "request",
]