# API Interfaces to control the simulator
#
# @author n1ghts4kura
# @date 2026-3-15
#

import json
import os
import atexit
import threading
import time
from uuid import uuid4
from enum import Enum
from pydantic import BaseModel, Field
from websocket import create_connection, WebSocketTimeoutException

from src.logger import make_logger
logger = make_logger("simulator")


# === Types ===
# 1. Action Types: modify the state of the bot (e.g., move, rotate, fire)
# 2. Response Types: provide feedback on the result of an action (e.g., success, failure, error message)
# =============


class Action(BaseModel):
    """Basic API Action Interface"""

    request_id: str = Field(default_factory=lambda: uuid4().hex, description="A unique ID for this action request, generated automatically if not provided")

    team: str = Field(..., description="Team the bot belongs to, either 'red' or 'blue'")

    timeout: int = Field(
        default=-1,
        ge=-1,
        description=(
            "Execution timeout budget in milliseconds for Unity-side action processing. "
            "Use -1 to wait indefinitely (no execution deadline)."
        ),
    )

    def to_datapacket_str(self) -> str:
        """
        Convert an Action instance to a dictionary format suitable for sending as a data packet to the simulator.

        Format:
        ```
        {
            "request_id": "an_unique_id_for_this_request", # always required; generated through `uuid.uuid4()`   
            "timeout": 5000, # always required; execution timeout in milliseconds; -1 means wait indefinitely
            "team": "red", # or "blue"; always required; should be set by the client based on the team the bot belongs to  
            "command": "the_command_name", # always required; same as the class name of the Action (e.g., "ChassisForwardAction")  
            "value": "...", # the content of the Action instance converted to a dictionary; always required; should be generated by the `dict()` method of the Action instance  
        }
        ```
        """

        command = self.__class__.__name__ # dynamic because of INHERITANCE
        value = self.model_dump(exclude={"request_id", "team", "timeout"}) # exclude common fields that are already included in the datapacket)

        datapacket = {
            "request_id": self.request_id,
            "timeout": self.timeout,
            "team": self.team,
            "command": command,
            "value": value,
        }

        return json.dumps(datapacket, ensure_ascii=False)
    

class Response(BaseModel):
    """Basic API Response Interface"""

    request_id: str = Field(..., description="The unique ID of the corresponding request/action that this response is for")

    success: bool = Field(..., description="Indicates if the action was successful")

    # value: str = Field("", description="The content of the response, which can be a success message, error message, or any relevant information returned by the simulator")


class StringResponse(Response):
    """A simple Response type where the value is just a string message"""

    value: str = Field("", description="The content of the response as a string, which can be a success message, error message, or any relevant information returned by the simulator")


class FloatResponse(Response):
    """A simple Response type where the value is a float number"""

    value: float = Field(0.0, description="The content of the response as a float number, which can be any relevant information returned by the simulator (e.g., current speed, angle, etc.)")


class IntResponse(Response):
    """A simple Response type where the value is an integer."""

    value: int = Field(0, description="The content of the response as an integer value")


# --- 1. Settings ---
# - (1) Bot Control Mode Settings

class BotControlMode(str, Enum):
    """Enumeration for Bot Control Modes"""

    INDEPENDENT = "independent" # Chassis and turret can be controlled independently
    CHASSIS_FOLLOW_TURRET = "chassis_follow_turret" # Chassis follows turret direction
    TURRET_FOLLOW_CHASSIS = "turret_follow_chassis" # Turret follows chassis direction


class BotControlModeSetAction(Action):
    """API Interface for Bot Control Mode Action"""

    mode: BotControlMode = Field(..., description="Bot control mode to set")


class BotControlModeGetAction(Action):
    """API Interface for Get Bot Control Mode Action"""

    pass


# - (2) Bot Speed Settings

class ChassisLinearSpeedSetAction(Action):
    """API Interface for Set Chassis Linear Speed Action"""

    speed: float = Field(..., description="Linear speed to set in meters per second")


class ChassisLinearSpeedGetAction(Action):
    """API Interface for Get Chassis Linear Speed Action"""

    pass


class ChassisAngularSpeedSetAction(Action):
    """API Interface for Set Chassis Angular Speed Action"""

    speed: float = Field(..., description="Angular speed to set in degrees per second")


class ChassisAngularSpeedGetAction(Action):
    """API Interface for Get Chassis Angular Speed Action"""

    pass


# - (3) Turret Pitch Limit

class TurretPitchLimitSetAction(Action):
    """API Interface for Set Turret Pitch Limit Action"""

    value: float = Field(..., description="Turret pitch limit to set in degrees. Both positive and negative values are allowed, representing the maximum pitch up and down angles respectively.")


class TurretPitchLimitGetAction(Action):
    """API Interface for Get Turret Pitch Limit Action"""

    pass


# - (4) Robot Status

class BotHealthGetAction(Action):
    """API Interface for Get Bot Health Action"""

    pass


class BotHealthSetAction(Action):
    """API Interface for Set Bot Health Action"""

    value: int = Field(..., description="Target bot health value")


class BotAmmoGetAction(Action):
    """API Interface for Get Bot Ammo Action"""

    pass


class BotAmmoSetAction(Action):
    """API Interface for Set Bot Ammo Action"""

    value: int = Field(..., ge=0, description="Target bot ammo value, must be >= 0")


# ------------------
# --- 2. Actions ---
# - (1) Chassis

class ChassisForwardAction(Action):
    """
    API Interface for Chassis Forward Action
    """

    distance: float = Field(..., description="Distance to move forward in meters")


class ChassisBackwardAction(Action):
    """API Interface for Chassis Backward Action"""

    distance: float = Field(..., description="Distance to move backward in meters")


class ChassisStrafeLeftAction(Action):
    """API Interface for Chassis Strafe Left Action"""

    distance: float = Field(..., description="Distance to strafe left in meters")


class ChassisStrafeRightAction(Action):
    """API Interface for Chassis Strafe Right Action"""

    distance: float = Field(..., description="Distance to strafe right in meters")


class ChassisRotateClockwiseAction(Action   ):
    """API Interface for Chassis Rotate Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate clockwise in degrees")


class ChassisRotateCounterClockwiseAction(Action):
    """API Interface for Chassis Rotate Counter-Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate counter-clockwise in degrees")


# - (2) Turret


class TurretRotateClockwiseAction(Action):
    """API Interface for Turret Rotate Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate turret clockwise in degrees")


class TurretRotateCounterClockwiseAction(Action):
    """API Interface for Turret Rotate Counter-Clockwise Action"""

    angle: float = Field(..., description="Angle to rotate turret counter-clockwise in degrees")


class TurretRotatePitchAction(Action):
    """API Interface for Turret Pitch Up Action"""

    angle: float = Field(..., description="Angle to pitch turret up in degrees")


class TurretFireAction(Action):
    """API Interface for Turret Fire Action"""

    pass


# ===========

_BASE_URL = os.getenv("SIMULATOR_WS_URL", "ws://localhost:8765/ws")
_CONN_TIMEOUT = 1000 * 60 * 10 # default timeout for connection attempts in milliseconds
_WS_ORIGIN = os.getenv("SIMULATOR_WS_ORIGIN")
_WS_SUBPROTOCOL = os.getenv("SIMULATOR_WS_SUBPROTOCOL")


class _PendingRequest:
    def __init__(self):
        self.event = threading.Event()
        self.response = None


class _PersistentWsClient:
    """Long-lived WebSocket client for request/response communication."""

    def __init__(self):
        self._ws = None
        self._state = "DISCONNECTED"
        self._state_lock = threading.Lock()
        self._connect_lock = threading.Lock()
        self._send_lock = threading.Lock()
        self._pending_lock = threading.Lock()
        self._pending = {}
        self._recv_thread = None
        self._stopping = False

    def _build_ws(self, url: str, timeout_sec: float):
        if _WS_ORIGIN and _WS_SUBPROTOCOL:
            return create_connection(
                url,
                timeout=timeout_sec,
                origin=_WS_ORIGIN,
                subprotocols=[_WS_SUBPROTOCOL],
            )
        if _WS_ORIGIN:
            return create_connection(
                url,
                timeout=timeout_sec,
                origin=_WS_ORIGIN,
            )
        if _WS_SUBPROTOCOL:
            return create_connection(
                url,
                timeout=timeout_sec,
                subprotocols=[_WS_SUBPROTOCOL],
            )
        return create_connection(url, timeout=timeout_sec)

    def _set_state(self, state: str):
        with self._state_lock:
            self._state = state

    def _get_state(self) -> str:
        with self._state_lock:
            return self._state

    def _is_connected(self) -> bool:
        with self._state_lock:
            return self._state == "CONNECTED" and self._ws is not None

    def _fail_all_pending(self, reason: str):
        with self._pending_lock:
            pending_items = list(self._pending.items())
            self._pending.clear()

        for _, pending in pending_items:
            pending.response = reason
            pending.event.set()

    def _handle_disconnect(self, reason: str):
        self._set_state("DISCONNECTED")

        ws = self._ws
        self._ws = None
        if ws is not None:
            try:
                ws.close()
            except Exception:
                pass

        self._fail_all_pending(reason)

    def _recv_loop(self):
        while not self._stopping:
            ws = self._ws
            if ws is None:
                break

            try:
                message = ws.recv()
            except WebSocketTimeoutException:
                continue
            except Exception as e:
                if self._stopping or self._get_state() == "STOPPING":
                    logger.debug("Persistent WebSocket recv loop exited during stopping")
                    break

                logger.error(f"Persistent WebSocket recv failed: {e}")
                self._handle_disconnect(f"error: transport exception: {str(e)}")
                break

            if message is None:
                if self._stopping or self._get_state() == "STOPPING":
                    logger.debug("Persistent WebSocket recv got None during stopping")
                    break
                self._handle_disconnect("error: transport exception: connection closed by peer")
                break

            if isinstance(message, (bytes, bytearray)):
                try:
                    message = message.decode("utf-8").strip()
                except UnicodeDecodeError:
                    logger.debug("Persistent WebSocket ignored non-UTF8 binary frame")
                    continue
            elif isinstance(message, str):
                message = message.strip()
            else:
                logger.debug(
                    f"Persistent WebSocket ignored non-text frame type={type(message).__name__}"
                )
                continue

            if not message:
                if self._stopping or self._get_state() == "STOPPING":
                    logger.debug("Persistent WebSocket recv got empty payload during stopping")
                    break
                self._handle_disconnect("error: transport exception: connection closed by peer")
                break

            try:
                payload = json.loads(message)
            except Exception:
                if self._stopping or self._get_state() == "STOPPING":
                    logger.debug("Persistent WebSocket ignored non-JSON payload during stopping")
                else:
                    logger.debug("Persistent WebSocket ignored non-JSON payload")
                continue

            request_id = payload.get("request_id")
            if not request_id:
                logger.debug("Persistent WebSocket ignored payload without request_id")
                continue

            with self._pending_lock:
                pending = self._pending.pop(request_id, None)

            if pending is None:
                logger.debug(
                    f"No pending waiter found for request_id={request_id}, response ignored"
                )
                continue

            pending.response = message
            pending.event.set()

    def _ensure_connected(self, url: str, conn_timeout: int):
        if self._is_connected():
            return

        with self._connect_lock:
            if self._is_connected():
                return

            self._set_state("CONNECTING")
            # timeout_sec = max(conn_timeout / 1000, 0.1)
            timeout_sec = conn_timeout / 1000
            attempts = 3
            backoff = [0.2, 0.5, 1.0]
            last_error = None

            for idx in range(attempts):
                try:
                    ws = self._build_ws(url, timeout_sec)
                    ws.settimeout(1.0)
                    self._ws = ws
                    self._set_state("CONNECTED")

                    self._recv_thread = threading.Thread(
                        target=self._recv_loop,
                        name="simulator-ws-recv",
                        daemon=True,
                    )
                    self._recv_thread.start()
                    logger.info(f"Persistent WebSocket connected to {url}")
                    return
                except Exception as e:
                    last_error = e
                    logger.error(
                        f"Persistent WebSocket connect attempt {idx + 1}/{attempts} failed: {e}"
                    )
                    if idx < attempts - 1:
                        time.sleep(backoff[idx])

            self._set_state("DISCONNECTED")
            raise RuntimeError(str(last_error) if last_error is not None else "unknown connect error")

    def request(self, action: Action, url: str, conn_timeout: int) -> str:
        if self._stopping:
            return _local_error_response(action, "error: transport exception: client is stopping")

        try:
            self._ensure_connected(url, conn_timeout)
        except Exception as e:
            logger.error(f"Persistent WebSocket ensure-connected failed: {e}")
            return _local_error_response(action, f"error: transport exception: {str(e)}")

        pending = _PendingRequest()
        with self._pending_lock:
            self._pending[action.request_id] = pending

        try:
            with self._send_lock:
                ws = self._ws
                if ws is None:
                    raise RuntimeError("connection lost before send")
                ws.send(action.to_datapacket_str())
        except Exception as e:
            with self._pending_lock:
                self._pending.pop(action.request_id, None)

            logger.error(f"Persistent WebSocket send failed: {e}")
            self._handle_disconnect(f"error: transport exception: {str(e)}")
            return _local_error_response(action, f"error: transport exception: {str(e)}")

        if not pending.event.wait(max(conn_timeout / 1000, 0.001)):
            with self._pending_lock:
                self._pending.pop(action.request_id, None)
            logger.error(
                f"Persistent WebSocket transport timed out after {conn_timeout} ms for request_id={action.request_id}"
            )
            return _local_error_response(action, f"error: transport timeout ({conn_timeout} ms)")

        response = pending.response
        if response is None:
            return _local_error_response(action, "error: transport exception: empty response")

        if response.startswith("error:"):
            return _local_error_response(action, response)

        return response

    def close(self):
        self._stopping = True
        self._set_state("STOPPING")
        self._handle_disconnect("error: transport exception: connection closed")

        thread = self._recv_thread
        if thread is not None and thread.is_alive():
            thread.join(timeout=1.0)


_PERSISTENT_CLIENT = _PersistentWsClient()
atexit.register(_PERSISTENT_CLIENT.close)


def _local_error_response(action: Action, message: str) -> str:
    """Build a JSON response for transport-layer failures on Python side."""

    return json.dumps(
        {
            "request_id": action.request_id,
            "success": False,
            "value": message,
        },
        ensure_ascii=False,
    )

def request(
    action: Action,
    url: str = _BASE_URL,
    conn_timeout: int = _CONN_TIMEOUT,
) -> str:
    """
    Send an Action to the Unity simulator via WebSocket and receive a Response.

    Args:
        action (Action): The Action instance to send to the simulator.
        url (str, optional): The WebSocket URL of the simulator. Defaults to _BASE_URL.
        conn_timeout (int, optional): Timeout for connection and socket I/O in milliseconds. Defaults to _CONN_TIMEOUT.

    Notes:
        `action.timeout` is forwarded to Unity as execution timeout budget.
        `action.timeout=-1` means no execution deadline (wait indefinitely on Unity side).
        `conn_timeout` is local Python transport timeout and is independent from `action.timeout`.

    Returns:
        str: The raw response string received from the simulator. In a real implementation, you would typically parse this into a Response object.
    """

    logger.debug(f"Sending action to simulator: {action}")
    return _PERSISTENT_CLIENT.request(action=action, url=url, conn_timeout=conn_timeout)


def close_connection() -> None:
    """Close persistent simulator WebSocket connection."""

    _PERSISTENT_CLIENT.close()


__all__ = [
    "Action",
    "Response",
    "StringResponse",
    "IntResponse",
    "BotControlMode",
    "BotControlModeSetAction",
    "BotControlModeGetAction",
    "FloatResponse",
    "ChassisLinearSpeedSetAction", 
    "ChassisLinearSpeedGetAction",
    "ChassisAngularSpeedSetAction",
    "ChassisAngularSpeedGetAction",
    "TurretPitchLimitSetAction",
    "TurretPitchLimitGetAction",
    "BotHealthGetAction",
    "BotHealthSetAction",
    "BotAmmoGetAction",
    "BotAmmoSetAction",
    "ChassisForwardAction",
    "ChassisBackwardAction",
    "ChassisStrafeLeftAction",
    "ChassisStrafeRightAction",
    "ChassisRotateClockwiseAction",
    "ChassisRotateCounterClockwiseAction",
    "TurretRotateClockwiseAction",
    "TurretRotateCounterClockwiseAction",
    "TurretRotatePitchAction",
    "TurretFireAction",
    "request",
    "close_connection",
]